package GUI;

import com.mycompany.conversorunidades.listaIconos;
import com.mycompany.conversorunidades.listaOpciones;
import com.mycompany.conversorunidades.longitudes;
import com.mycompany.conversorunidades.monedas;
import com.mycompany.conversorunidades.temperatura;
import javax.swing.JOptionPane;

/**
 *
 * @author solgaleo
 */
public class interfazApp extends javax.swing.JFrame {

    listaIconos iconos = new listaIconos();
    listaOpciones opciones = new listaOpciones();
    
    
    monedas divisas = new monedas();
    longitudes longitud = new longitudes();
    temperatura grados = new temperatura();
    
    public interfazApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPrincipal = new javax.swing.JPanel();
        contenedorLogo = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        contenedorLista = new javax.swing.JPanel();
        listaConversores = new javax.swing.JList<>();
        tituloSelector = new javax.swing.JLabel();
        contenedorValores = new javax.swing.JPanel();
        valorEntrada = new javax.swing.JTextField();
        valorSalida = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        unidadEntrada = new javax.swing.JComboBox<>();
        unidadSalida = new javax.swing.JComboBox<>();
        tituloVariable = new javax.swing.JLabel();
        imagenVariable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenu();
        Divisas = new javax.swing.JMenuItem();
        Longitud = new javax.swing.JMenuItem();
        Temperatura = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Unidades CODE");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(500, 350));
        setResizable(false);

        contenedorPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        contenedorLogo.setBackground(new java.awt.Color(51, 51, 51));

        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon("/home/solgaleo/NetBeansProjects/conversorUnidades/src/main/java/imagenesApp/logo_1.png")); // NOI18N

        javax.swing.GroupLayout contenedorLogoLayout = new javax.swing.GroupLayout(contenedorLogo);
        contenedorLogo.setLayout(contenedorLogoLayout);
        contenedorLogoLayout.setHorizontalGroup(
            contenedorLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLogoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenedorLogoLayout.setVerticalGroup(
            contenedorLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLogoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        contenedorLista.setBackground(new java.awt.Color(51, 51, 51));

        listaConversores.setBackground(new java.awt.Color(51, 51, 51));
        listaConversores.setBorder(null);
        listaConversores.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 16)); // NOI18N
        listaConversores.setForeground(new java.awt.Color(255, 255, 255));
        listaConversores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "» Divisas", "» Longitud", "» Temperatura" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaConversores.setAutoscrolls(false);
        listaConversores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaConversoresValueChanged(evt);
            }
        });

        tituloSelector.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 16)); // NOI18N
        tituloSelector.setForeground(new java.awt.Color(255, 255, 255));
        tituloSelector.setText("Selecciona uno:");

        javax.swing.GroupLayout contenedorListaLayout = new javax.swing.GroupLayout(contenedorLista);
        contenedorLista.setLayout(contenedorListaLayout);
        contenedorListaLayout.setHorizontalGroup(
            contenedorListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorListaLayout.createSequentialGroup()
                        .addComponent(tituloSelector)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorListaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(listaConversores, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        contenedorListaLayout.setVerticalGroup(
            contenedorListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorListaLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(tituloSelector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaConversores, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        contenedorValores.setBackground(new java.awt.Color(51, 51, 51));
        contenedorValores.setAutoscrolls(true);

        valorEntrada.setBackground(new java.awt.Color(153, 153, 153));
        valorEntrada.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 16)); // NOI18N
        valorEntrada.setForeground(new java.awt.Color(255, 255, 255));
        valorEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valorEntrada.setCaretColor(new java.awt.Color(255, 255, 255));
        valorEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorEntradaActionPerformed(evt);
            }
        });

        valorSalida.setEditable(false);
        valorSalida.setBackground(new java.awt.Color(153, 153, 153));
        valorSalida.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 16)); // NOI18N
        valorSalida.setForeground(new java.awt.Color(255, 255, 255));
        valorSalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valorSalida.setCaretColor(new java.awt.Color(255, 255, 255));

        btnConvertir.setBackground(new java.awt.Color(102, 102, 102));
        btnConvertir.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 12)); // NOI18N
        btnConvertir.setForeground(new java.awt.Color(255, 255, 255));
        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        unidadEntrada.setBackground(new java.awt.Color(102, 102, 102));
        unidadEntrada.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        unidadEntrada.setForeground(new java.awt.Color(255, 255, 255));
        unidadEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona uno" }));
        unidadEntrada.setAutoscrolls(true);
        unidadEntrada.setBorder(null);

        unidadSalida.setBackground(new java.awt.Color(102, 102, 102));
        unidadSalida.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        unidadSalida.setForeground(new java.awt.Color(255, 255, 255));
        unidadSalida.setAutoscrolls(true);
        unidadSalida.setBorder(null);

        tituloVariable.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 16)); // NOI18N
        tituloVariable.setForeground(new java.awt.Color(255, 255, 255));
        tituloVariable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVariable.setText("Divisas");

        imagenVariable.setBackground(new java.awt.Color(255, 255, 255));
        imagenVariable.setForeground(new java.awt.Color(255, 255, 255));
        imagenVariable.setIcon(new javax.swing.ImageIcon("/home/solgaleo/NetBeansProjects/conversorUnidades/src/main/java/imagenesApp/monedas1.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Conversor de");

        javax.swing.GroupLayout contenedorValoresLayout = new javax.swing.GroupLayout(contenedorValores);
        contenedorValores.setLayout(contenedorValoresLayout);
        contenedorValoresLayout.setHorizontalGroup(
            contenedorValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorValoresLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imagenVariable)
                .addGap(33, 33, 33)
                .addGroup(contenedorValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(contenedorValoresLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(tituloVariable)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorValoresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(contenedorValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(unidadSalida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unidadEntrada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valorEntrada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(valorSalida, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorValoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConvertir)
                .addGap(99, 99, 99))
        );
        contenedorValoresLayout.setVerticalGroup(
            contenedorValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorValoresLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(contenedorValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorValoresLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tituloVariable))
                    .addComponent(imagenVariable))
                .addGap(31, 31, 31)
                .addComponent(valorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(unidadEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(valorSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unidadSalida)
                .addGap(18, 18, 18)
                .addComponent(btnConvertir)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout contenedorPrincipalLayout = new javax.swing.GroupLayout(contenedorPrincipal);
        contenedorPrincipal.setLayout(contenedorPrincipalLayout);
        contenedorPrincipalLayout.setHorizontalGroup(
            contenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPrincipalLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(contenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedorLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contenedorLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contenedorPrincipalLayout.setVerticalGroup(
            contenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorPrincipalLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(contenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorPrincipalLayout.createSequentialGroup()
                        .addComponent(contenedorLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenedorLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(contenedorValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        barraMenu.setBackground(new java.awt.Color(204, 204, 204));
        barraMenu.setBorder(null);
        barraMenu.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N

        Archivo.setText("Archivo");
        Archivo.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N

        Salir.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Archivo.add(Salir);

        barraMenu.add(Archivo);

        Editar.setText("Editar");
        Editar.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N

        Divisas.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        Divisas.setText("Divisas");
        Divisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisasActionPerformed(evt);
            }
        });
        Editar.add(Divisas);

        Longitud.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        Longitud.setText("Longitud");
        Longitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LongitudActionPerformed(evt);
            }
        });
        Editar.add(Longitud);

        Temperatura.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        Temperatura.setText("Temperatura");
        Temperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemperaturaActionPerformed(evt);
            }
        });
        Editar.add(Temperatura);

        barraMenu.add(Editar);

        Ayuda.setText("Ayuda");
        Ayuda.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N

        About.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        About.setText("Acerca de");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        Ayuda.add(About);

        barraMenu.add(Ayuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        boolean flat1 = this.esNumero(valorEntrada.getText());
        if(flat1){
            double resultado;
            switch (listaConversores.getSelectedIndex()) {
                case 0:
                    resultado = divisas.conversion(Double.parseDouble(valorEntrada.getText()), unidadEntrada.getSelectedItem().toString(), unidadSalida.getSelectedItem().toString());
                    valorSalida.setText(String.valueOf(Math.round(resultado * 10000.00)/10000.00));
                    break;
                case 1:
                    resultado = longitud.convertirEn(Double.parseDouble(valorEntrada.getText()), unidadEntrada.getSelectedItem().toString(), unidadSalida.getSelectedItem().toString());
                    valorSalida.setText(String.valueOf(Math.round(resultado * 10000.00)/10000.00));
                    break;
                case 2:
                    resultado = grados.selector(Double.valueOf(valorEntrada.getText()),unidadEntrada.getSelectedItem().toString(), unidadSalida.getSelectedItem().toString());
                    valorSalida.setText(String.valueOf(Math.round(resultado * 10000.00)/10000.00));
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Selecciona un tipo de convertidor de la lista");
            }

        }else{
             JOptionPane.showMessageDialog(this, "No es un Numero Valido");
        }
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void listaConversoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaConversoresValueChanged
        tituloVariable.setText(listaConversores.getSelectedValue().replaceAll("[^a-z^A-Z]", "")); 
        imagenVariable.setIcon(iconos.cambiarIcono(listaConversores.getSelectedIndex()));
        unidadEntrada.removeAllItems();
        unidadSalida.removeAllItems();
        for (Object element : opciones.cambiarOpciones(listaConversores.getSelectedIndex())) {
            unidadEntrada.addItem((String) element);
            unidadSalida.addItem((String) element);
        }

    }//GEN-LAST:event_listaConversoresValueChanged

    private void valorEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorEntradaActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        String mensaje;
        mensaje = "**************************************\n" +
"  Programa ONE Alura Latiniamerica\n" +
"  [1] Programa: Conversor de Unidades CODE\n" +
"  [2] Version: 1.0\n" +
"  [3] Autor: EtebanBTR\n" +
"  [4] GitHub: https://gist.github.com/MyProyectlist \n"+
"  [5] Linkedig: https://www.linkedin.com/in/estebantr \n" +
"**************************************";
         
        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_AboutActionPerformed

    private void DivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisasActionPerformed
        listaConversores.setSelectedIndex(0);
    }//GEN-LAST:event_DivisasActionPerformed

    private void LongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LongitudActionPerformed
        listaConversores.setSelectedIndex(1);
    }//GEN-LAST:event_LongitudActionPerformed

    private void TemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemperaturaActionPerformed
        listaConversores.setSelectedIndex(2);
    }//GEN-LAST:event_TemperaturaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

public boolean esNumero(String label) {
        for(int i = 0; i < label.length();i++){
            int num = label.codePointAt(i);
            if(num >= 48 && num <= 57){
                return true;
            }
        }
        return false;
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenuItem Divisas;
    private javax.swing.JMenu Editar;
    private javax.swing.JMenuItem Longitud;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem Temperatura;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JPanel contenedorLista;
    private javax.swing.JPanel contenedorLogo;
    private javax.swing.JPanel contenedorPrincipal;
    private javax.swing.JPanel contenedorValores;
    private javax.swing.JLabel imagenVariable;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> listaConversores;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel tituloSelector;
    private javax.swing.JLabel tituloVariable;
    private javax.swing.JComboBox<String> unidadEntrada;
    private javax.swing.JComboBox<String> unidadSalida;
    private javax.swing.JTextField valorEntrada;
    private javax.swing.JTextField valorSalida;
    // End of variables declaration//GEN-END:variables
}
